
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author saadr
 */
public class NewStudent extends javax.swing.JFrame {

    /**
     * Creates new form NewStudent
     */
    public NewStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nameAD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FatherNameAD = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        genderAD = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        cellAD = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        classAD = new javax.swing.JComboBox<>();
        secAD = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        studentDateChoose = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressAD = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        Background_newStudent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Management System \\ New Student");
        setMinimumSize(new java.awt.Dimension(500, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 600));

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 600));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Add New Student");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 50, 200, 40);

        jButton1.setText("Add");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 500, 90, 30);

        jButton2.setText("Cancel");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(240, 500, 90, 30);

        nameAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameADActionPerformed(evt);
            }
        });
        jPanel1.add(nameAD);
        nameAD.setBounds(160, 110, 260, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Date of Birth :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 210, 90, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Name : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 110, 60, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Father's Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 160, 100, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Gender :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 260, 60, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Cell Phone No :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 310, 110, 30);

        FatherNameAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNameADActionPerformed(evt);
            }
        });
        jPanel1.add(FatherNameAD);
        FatherNameAD.setBounds(160, 160, 260, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(50, 150, 400, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(50, 200, 400, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(50, 250, 400, 10);

        genderAD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female" }));
        jPanel1.add(genderAD);
        genderAD.setBounds(160, 260, 260, 30);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(50, 300, 400, 10);

        cellAD.setText("+92");
        cellAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellADActionPerformed(evt);
            }
        });
        jPanel1.add(cellAD);
        cellAD.setBounds(160, 310, 260, 30);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(50, 350, 400, 10);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(50, 100, 400, 10);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Address :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 370, 60, 30);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(50, 420, 400, 10);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Class :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 430, 50, 30);

        classAD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        classAD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Standard", "2nd Standard", "3rd Standard", "4th Standard", "5th Standard", "6th Standard", "7th Standard", "8th Standard", "9th Standard", "10th Standard" }));
        jPanel1.add(classAD);
        classAD.setBounds(130, 430, 120, 30);

        secAD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L" }));
        secAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secADActionPerformed(evt);
            }
        });
        jPanel1.add(secAD);
        secAD.setBounds(330, 430, 50, 30);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(50, 470, 400, 10);
        jPanel1.add(studentDateChoose);
        studentDateChoose.setBounds(160, 210, 260, 30);

        addressAD.setColumns(20);
        addressAD.setRows(5);
        jScrollPane1.setViewportView(addressAD);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 360, 260, 50);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Section :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 430, 60, 30);

        Background_newStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newstudent-02.jpg"))); // NOI18N
        jPanel1.add(Background_newStudent);
        Background_newStudent.setBounds(0, 0, 500, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FatherNameADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNameADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherNameADActionPerformed

    private void nameADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameADActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void secADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secADActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String filePath = "stdentRecordFiles.txt";
        File file = new File(filePath);
        String date01 = studentDateChoose.getDate().toString() ;
        String split01[] = date01.split(" ");
        String date = split01[2]+"-"+split01[1]+"-"+split01[5];
        FileWriter fw;
        try {
            fw = new FileWriter(file,true);
            fw.write(nameAD.getText()+"#"+FatherNameAD.getText()+"#"+date+"#"+genderAD.getSelectedItem().toString()+"#"+cellAD.getText()+"#"+addressAD.getText()+"#"+classAD.getSelectedItem().toString()+"-"+secAD.getSelectedItem().toString()+"#\n");
            fw.close();
            
        } 
        catch (IOException ex) {
            Logger.getLogger(NewStudent.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Error: Studend is Not Added.");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error: Studend is Not Added.");
            
        }
        int option = JOptionPane.showConfirmDialog(this,"Studend Add Successfully.\n"+"Want to add another:");
        switch (option) {
            case JOptionPane.YES_OPTION:
                this.dispose();
                new NewStudent().setVisible(true);
                break;
            case JOptionPane.NO_OPTION:
                this.dispose();
                break;
            case JOptionPane.CANCEL_OPTION:
                this.dispose();
                break;
            default:
                break;
        }
        
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cellADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellADActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background_newStudent;
    private javax.swing.JTextField FatherNameAD;
    private javax.swing.JTextArea addressAD;
    private javax.swing.JTextField cellAD;
    private javax.swing.JComboBox<String> classAD;
    private javax.swing.JComboBox<String> genderAD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField nameAD;
    private javax.swing.JComboBox<String> secAD;
    private com.toedter.calendar.JDateChooser studentDateChoose;
    // End of variables declaration//GEN-END:variables
}
